### PR TITLE
fix install script

### LINKED ISSUE #73: make install apt sources not changed to packages.bit-bots.de
The make install script still uses the normal ros surces

## Expected behavior
Use packages.bit-bots.de or ask which one you want

## Current behavior
Using normal ros sources and thus leading to errors when packages.bit-bots is also listed as source

### LINKED ISSUE #81: Fix install script
Fix the install script, to install all the dependencies (manual, without rosdep).

## Expected behavior
Setup everything.

## Current behavior
Failes.

## Context (Environment)
- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [X] Local

### PR DESCRIPTION
**Pull request by timonegk**
## Proposed changes
Fixes install script. Not tested yet.

## Related issues
Closes #73 and closes #81.

## Necessary checks
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Comment by timonegk** [comment]
I tested the script in a fresh docker container and it works.

File: scripts/install.pl [hunk 1]
```diff
@@ -94,13 +99,18 @@ ()
...
+    if (! -e "/etc/apt/sources.list.d/ros.list") {
+        system "sudo sh -c 'echo \"deb http://packages.bit-bots.de bionic main\" > /etc/apt/sources.list.d/ros.list'"
             and die "Unable to add ROS sources";
     }
-    system "sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"
+    system "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 4C4EDF893374591687621C75C2F8DBB6A37B2874"
         or system "sudo apt update"
-        or system "sudo apt install -y python-catkin-tools python-rosdep"
+        or system "sudo apt install -y python3-pip python3-rosdep"
+    or system "sudo pip3 install git+https://github.com/catkin/catkin_tools.git"
```
Comment (ftsell) [inline scripts/install.pl:113]: Why as root? Is `pip3 install --user` not more appropriate?

File: scripts/install.pl [hunk 2]
```diff
@@ -134,36 +143,50 @@ ()
...
     }
 }
 
-
 sub clone_internal_repos() {
     # Clone internal bitbots_repos into bitbots_meta
     chdir $start_dir;
 
-    print "Do you want to clone bitbots gogs repos ('ansible_robots', 'doku', 'basler_drivers') now?$/";
+    print "Do you want to clone the private repos ('ansible_robots', 'doku' and 'basler_drivers') now?$/";
```
Comment (ftsell) [inline scripts/install.pl:154]: It is now only called `ansible`

File: scripts/install.pl [hunk 3]
```diff
@@ -134,36 +143,50 @@ ()
...
     print "[Y/n]: ";
     if (read_yes_no_input()) {
-        system 'git clone gogs@gogs.mafiasi.de:Bit-Bots/ansible_robots.git'
+    if (! -e "ansible") {
+        system 'git clone git@git.mafiasi.de:Bit-Bots/ansible.git'
```
Comment (ftsell) [inline scripts/install.pl:158]: I personally have ansible cloned into bitbots_tools because there it is registered in the .gitigignore file. We might want to do the same here too

File: scripts/install.pl [hunk 4]
```diff
@@ -134,36 +143,50 @@ ()
...
             and print "Could not clone ansible_robots$/$/";
+    } else {
+        print "ansible is already cloned$/";
+        }
 
-        system 'git clone gogs@gogs.mafiasi.de:Bit-Bots/doku.git'
-            and print "Could not clone doku$/$/";
+    if (! -e "doku") {
+            system 'git clone git@git.mafiasi.de:Bit-Bots/doku.git'
```
Comment (ftsell) [inline scripts/install.pl:165]: I personally have the internal docs cloned into bitbots_tools as bitbots_docs_internal because it is registered in the .gitignore file there. We might want to do the same here too

**Review by ftsell — CHANGES_REQUESTED** [review]

File: scripts/install.pl (hunk 1 above)
Comment (timonegk) [reply scripts/install.pl:113]: Maybe. But many (especially new) users don't have `~/.local/bin` in their `PATH`, so I figured it would be easier to just install it globally (and it doesn't interfere with system packages because `pip` installs to `/usr/local/`).

Comment (ftsell) [reply scripts/install.pl:113]: hmm, alright

**Review by ftsell — DISMISSED** [review]

**Comment by timonegk** [comment]
I added a cleanup of the `scripts` folder and the `Makefile`. I removed the `make build` because I never heard that anybody used it and removed the scripts `build.sh` (for the same reason), `create_venv.bash` (also unused), `install_py_extension.bash` (is now done via cmake) and `repair.sh` (fortunately not needed anymore).

**Review by ftsell — APPROVED** [review]
